export const CREATE_GAME_BOARD = "CREATE_GAME_BOARD";
export const SELECT_FIRST_TILE = "SELECT_FIRST_TILE";
export const SELECT_SECOND_TILE = "SELECT_SECOND_TILE";
export const SELECT_SECOND_TILE_FAILURE_BEGIN =
	"SELECT_SECOND_TILE_FAILURE_BEGIN ";
export const SELECT_SECOND_TILE_FAILURE = "SELECT_SECOND_TILE_FAILURE";
export const FINISH_GAME = "FINISH_GAME";
export const SEE_RESULT = "SEE_RESULT";
